name: Deploy API Documentation to Bump.sh

on:
  push:
    branches: [main]
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - '**/components/*.yaml'
  workflow_dispatch:

jobs:
  deploy-to-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Bump.sh CLI
        run: |
          npm install -g bump-cli
          pip install --user pyyaml

      - name: Custom script for x-topics import
        run: |
          # Create a Python script for proper handling of YAML arrays
          cat > direct_replace.py << 'EOF'
          import re
          import os
          import sys
          import yaml

          def main():
              # Read the main OpenAPI file as text
              with open('openapi.yaml', 'r') as f:
                  content = f.read()
              
              # Load the topics file properly
              with open('topics.yaml', 'r') as f:
                  topics = yaml.safe_load(f)
              
              # Convert topics to proper YAML format
              topics_yaml = yaml.dump(topics, default_flow_style=False, indent=2).strip()
              
              # Create the proper replacement - first line needs special handling
              replacement = "x-topics:"
              
              # Add the topics content with proper indentation
              indented_content = ""
              for i, line in enumerate(topics_yaml.split('\n')):
                  if i == 0:  # First line needs special handling for array
                      if line.startswith('-'):
                          indented_content += f"\n  {line}"  # Add proper indentation for array
                      else:
                          indented_content += f" {line}"  # For non-array, add a space
                  else:
                      indented_content += f"\n  {line}"  # Indent all other lines with 2 spaces
              
              replacement += indented_content
              
              # Find the x-topics reference pattern
              pattern = r"x-topics:\s+\$ref:\s+['\"]?[\./\w-]+\.ya?ml['\"]?"
              
              # Replace the reference with our properly formatted content
              updated_content = re.sub(pattern, replacement, content)
              
              # Write the result to the output file
              with open('openapi-resolved.yaml', 'w') as f:
                  f.write(updated_content)
                  
              print("Successfully created openapi-resolved.yaml with proper YAML formatting")

          if __name__ == "__main__":
              main()
          EOF

          # Run the script
          python3 direct_replace.py

      - name: Validate YAML
        run: |
          echo "Validating the resolved YAML file..."
          python3 -c "import yaml; yaml.safe_load(open('openapi-resolved.yaml'))"

      - name: Deploy to Bump.sh
        id: deploy
        run: |
          echo "Deploying to Bump.sh..."
          bump deploy openapi-resolved.yaml --doc omni-v2
        env:
          BUMP_TOKEN: ${{ secrets.BUMP_TOKEN }}

      - name: Summary
        if: always()
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "* Original file: $(wc -c openapi.yaml | awk '{print $1}') bytes" >> $GITHUB_STEP_SUMMARY
          echo "* Resolved file: $(wc -c openapi-resolved.yaml | awk '{print $1}') bytes" >> $GITHUB_STEP_SUMMARY
          echo "* Status: ${{ steps.deploy.outcome }}" >> $GITHUB_STEP_SUMMARY
          echo "* Documentation URL: https://bump.sh/doc/omni-v2" >> $GITHUB_STEP_SUMMARY
