name: Bump.sh API Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-doc:
    name: Deploy API documentation to Bump.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug info and fix servers.yaml
        run: |
          echo "Current directory: $(pwd)"
          echo "Listing all YAML files to verify they exist:"
          find . -name "*.yaml" -type f | sort

          echo "Does servers.yaml exist? $(test -f servers.yaml && echo Yes || echo No)"

          # Check the actual content of servers.yaml
          echo "Content of servers.yaml (if it exists):"
          cat servers.yaml || echo "File not found"

          # Create or fix servers.yaml if needed
          echo "Creating/fixing servers.yaml:"
          echo "- url: https://api.omni.integratedcommerce.io/v1" > servers.yaml

          # Verify the file was created/fixed
          echo "Content of servers.yaml after fix:"
          cat servers.yaml

          # Verify all referenced files exist
          echo "Checking referenced files from openapi.yaml:"
          grep -r "\$ref:" openapi.yaml | sed "s/.*\$ref: '\(.*\)'.*/\1/" | while read file; do
            file="${file#./}"  # Remove leading ./ if present
            if [[ "$file" == *"#"* ]]; then
              # Extract just the file path before any #
              file_path="${file%%#*}"
              echo "Referenced file path: $file_path - Exists? $(test -f "$file_path" && echo Yes || echo No)"
            else
              echo "Referenced file: $file - Exists? $(test -f "$file" && echo Yes || echo No)"
            fi
          done

      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: ${{ secrets.BUMP_DOC_ID }}
          token: ${{ secrets.BUMP_TOKEN }}
          file: openapi.yaml
