name: Deploy API Documentation to Bump.sh

on:
  push:
    branches: [main]
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  deploy-to-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files (Debug)
        run: |
          pwd
          ls -la
          echo "Looking for openapi.yaml:"
          find . -name "openapi.yaml" || echo "Not found"

      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: omni-v2
          token: ${{ secrets.BUMP_TOKEN }}
          file: ./openapi.yaml # Explicitly use relative path
