name: Deploy API Documentation to Bump.sh

on:
  push:
    branches: [main]
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  deploy-to-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files
        run: |
          echo "Repository contents:"
          ls -la
          echo "Content of topics.yaml:"
          cat topics.yaml || echo "topics.yaml not found"
          echo "Checking references in openapi.yaml:"
          grep -n "topics.yaml" openapi.yaml || echo "No reference to topics.yaml found"

      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: omni-v2
          token: ${{ secrets.BUMP_TOKEN }}
          file: openapi.yaml
