name: Deploy API Documentation to Bump.sh

on:
  push:
    branches: [main]
    paths:
      - '**/*.yaml'
      - '**/*.yml'
  workflow_dispatch:

jobs:
  deploy-to-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Bump.sh CLI and dependencies
        run: |
          npm install -g bump-cli
          pip install --user pyyaml

      - name: Create reference resolution script
        run: |
          cat > resolve.py << 'EOF'
          import yaml
          import os
          import sys

          def load_yaml(file_path):
              with open(file_path, 'r') as f:
                  return yaml.safe_load(f)

          def save_yaml(data, file_path):
              with open(file_path, 'w') as f:
                  yaml.dump(data, f, default_flow_style=False, sort_keys=False, width=200, allow_unicode=True)

          def main():
              # Load main file
              print("Loading OpenAPI file...")
              openapi = load_yaml('openapi.yaml')
              
              # Handle x-topics
              if 'x-topics' in openapi and isinstance(openapi['x-topics'], dict) and '$ref' in openapi['x-topics']:
                  topics_ref = openapi['x-topics']['$ref']
                  if topics_ref.startswith('./'):
                      topics_ref = topics_ref[2:]
                  
                  print(f"Loading topics from: {topics_ref}")
                  topics = load_yaml(topics_ref)
                  if topics:
                      openapi['x-topics'] = topics
              
              # Save the combined file
              save_yaml(openapi, 'openapi-resolved.yaml')
              print("Created combined OpenAPI file")

          if __name__ == "__main__":
              main()
          EOF

      - name: Run reference resolution
        run: python3 resolve.py

      - name: Deploy to Bump.sh
        id: deploy
        run: |
          echo "Deploying to Bump.sh..."
          bump deploy openapi-resolved.yaml --doc omni-v2
        env:
          BUMP_TOKEN: ${{ secrets.BUMP_TOKEN }}

      - name: Summary
        if: always()
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "* Original file: $(wc -c openapi.yaml | awk '{print $1}') bytes" >> $GITHUB_STEP_SUMMARY
          echo "* Resolved file: $(wc -c openapi-resolved.yaml | awk '{print $1}') bytes" >> $GITHUB_STEP_SUMMARY
          echo "* Status: ${{ steps.deploy.outcome }}" >> $GITHUB_STEP_SUMMARY
          echo "* Documentation URL: https://bump.sh/doc/omni-v2" >> $GITHUB_STEP_SUMMARY
