name: Bump.sh API Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-doc:
    name: Deploy API documentation to Bump.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug information
        run: |
          echo "Current directory:"
          pwd
          echo "Repository contents:"
          ls -la
          echo "Full path to servers.yaml:"
          realpath servers.yaml || echo "servers.yaml not found"

      - name: Set up working directory
        run: |
          # Copy everything to /tmp/api
          mkdir -p /tmp/api
          cp -r . /tmp/api/
          echo "Contents of /tmp/api:"
          ls -la /tmp/api/

      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        env:
          GITHUB_WORKSPACE: /tmp/api
        with:
          doc: ${{ secrets.BUMP_DOC_ID }}
          token: ${{ secrets.BUMP_TOKEN }}
          file: /tmp/api/openapi.yaml
