name: Deploy API Documentation to Bump.sh

on:
  push:
    branches: [main]
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  deploy-to-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Bump.sh CLI
        run: npm install -g bump-cli

      - name: List files
        run: |
          echo "Repository contents:"
          ls -la
          echo "Content of topics.yaml:"
          cat topics.yaml || echo "topics.yaml not found"

      - name: Deploy with Bump.sh CLI
        run: bump deploy openapi.yaml --doc omni-v2 --resolve-refs
        env:
          BUMP_TOKEN: ${{ secrets.BUMP_TOKEN }}
