name: Bump.sh API Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-doc:
    name: Deploy API documentation to Bump.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug information
        run: |
          echo "Current directory: $(pwd)"
          echo "All files in repository:"
          ls -la
          echo "YAML files:"
          find . -name "*.yaml" -type f | sort

      - name: Install swagger-cli for bundling
        run: npm install -g @apidevtools/swagger-cli

      - name: Bundle OpenAPI files
        run: |
          # Create a bundled file to avoid reference issues
          swagger-cli bundle openapi.yaml -o bundled.yaml
          echo "Created bundled.yaml file"

      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: ${{ secrets.BUMP_DOC_ID }}
          token: ${{ secrets.BUMP_TOKEN }}
          file: bundled.yaml
