name: Deploy API Documentation to Bump.sh

on:
  push:
    branches: [main]
    paths:
      - '**/*.yaml'
      - '**/*.yml'
  workflow_dispatch: # Allow manual triggering

jobs:
  deploy-to-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Fetch all history for proper versioning

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Use Node.js 20 as recommended by Bump.sh

      - name: Install Bump.sh CLI
        run: npm install -g bump-cli

      - name: Verify files
        run: |
          echo "Checking for required files..."
          [ -f "openapi.yaml" ] && echo "✓ openapi.yaml exists" || echo "✗ openapi.yaml missing"
          [ -f "topics.yaml" ] && echo "✓ topics.yaml exists" || echo "✗ topics.yaml missing"

          echo "Checking references in openapi.yaml..."
          grep -n "topics.yaml" openapi.yaml || echo "No reference to topics.yaml found"

      # Optional: Validate OpenAPI file before deployment
      - name: Validate OpenAPI
        run: |
          echo "Validating OpenAPI specification..."
          npx @stoplight/spectral-cli lint openapi.yaml || echo "Validation warnings detected, continuing deployment"

      # Deploy using Bump.sh CLI (recommended approach)
      - name: Deploy to Bump.sh
        run: |
          echo "Deploying to Bump.sh..."
          bump deploy openapi.yaml --doc omni-v2
        env:
          BUMP_TOKEN: ${{ secrets.BUMP_TOKEN }}

      # Optional: Add a comment to PRs with a preview link
      - name: Comment on PR
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `📚 API Documentation has been updated! View it at: https://bump.sh/doc/omni-v2`
            })
