name: Bump.sh API Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-doc:
    name: Deploy API documentation to Bump.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug and create missing files
        run: |
          echo "Current directory: $(pwd)"
          echo "All YAML files in repository:"
          find . -name "*.yaml" -type f | sort

          # Create servers.yaml if it doesn't exist
          echo "Creating servers.yaml:"
          echo "- url: https://api.omni.integratedcommerce.io/v1" > servers.yaml

          # Create basic files for each $ref in openapi.yaml
          echo "Creating basic files for references in openapi.yaml:"
          mkdir -p components/schemas components/parameters components/requestBodies components/responses components/examples components/securitySchemes
          mkdir -p paths tags

          # Create minimal versions of commonly referenced files
          echo "{}" > components/schemas/common.yaml
          echo "{}" > components/parameters.yaml
          echo "{}" > components/requestBodies.yaml
          echo "{}" > components/responses.yaml
          echo "{}" > components/examples.yaml
          echo "{}" > components/securitySchemes.yaml
          echo "{}" > tags/index.yaml

          # Create minimal versions of paths files
          echo "getPaymentMethods: {}" > paths/payment-methods.yaml
          echo "createCardPresentToken: {}" > paths/tokens.yaml
          echo "saleCardPresent: {}" > paths/transactions.yaml
          echo "SaleCompleted: {}" > paths/webhooks.yaml

          echo "Files created. Directory structure:"
          find . -type d | sort
          echo "YAML files after creation:"
          find . -name "*.yaml" -type f | sort

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install swagger-cli for bundling
        run: npm install -g @apidevtools/swagger-cli

      - name: Bundle OpenAPI files
        run: |
          # Bundle everything into a single file
          swagger-cli bundle openapi.yaml -o bundled.yaml

          # Check if bundling was successful
          if [ -f bundled.yaml ]; then
            echo "Bundling successful. First 20 lines of bundled.yaml:"
            head -n 20 bundled.yaml
          else
            echo "Bundling failed. No bundled.yaml file was created."
            exit 1
          fi

      - name: Deploy bundled documentation
        uses: bump-sh/github-action@v1
        with:
          doc: ${{ secrets.BUMP_DOC_ID }}
          token: ${{ secrets.BUMP_TOKEN }}
          file: bundled.yaml
