name: Deploy API Documentation to Bump.sh

on:
  push:
    branches: [main]
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  deploy-to-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Bump.sh CLI
        run: npm install -g bump-cli

      - name: Fix x-topics with Python
        run: |
          echo "Creating fixed OpenAPI file with Python..."
          python3 -c '
          import yaml, sys

          # Load the files
          with open("openapi.yaml", "r") as f:
              openapi = yaml.safe_load(f)
              
          with open("topics.yaml", "r") as f:
              topics = yaml.safe_load(f)

          # Replace the x-topics reference with the actual content
          openapi["x-topics"] = topics

          # Write the updated file
          with open("openapi-fixed.yaml", "w") as f:
              yaml.dump(openapi, f, default_flow_style=False)

          print("Successfully created openapi-fixed.yaml")
          '

      - name: Deploy using Bump.sh CLI
        run: bump deploy openapi-fixed.yaml --doc omni-v2
        env:
          BUMP_TOKEN: ${{ secrets.BUMP_TOKEN }}
