name: Deploy API Documentation to Bump.sh

on:
  push:
    branches: [main]
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  deploy-to-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Updated to Node.js 18 for compatibility

      - name: Install Bump.sh CLI
        run: npm install -g @bump.sh/cli

      - name: Debug file structure
        run: |
          find . -name "*.yaml" | sort
          cat servers.yaml

      - name: Deploy to Bump.sh with resolve-refs
        run: bump deploy openapi.yaml --doc omni-v2 --resolve-refs
        env:
          BUMP_TOKEN: ${{ secrets.BUMP_TOKEN }}
