name: Deploy API Documentation to Bump.sh

on:
  push:
    branches: [main]
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  deploy-to-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List files to debug
        run: find . -name "*.yaml" -o -name "*.yml" | sort

      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: omni-v2
          token: ${{ secrets.BUMP_TOKEN }}
          file: openapi.yaml
