name: Bump.sh API Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-doc:
    name: Deploy API documentation to Bump.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare directory structure
        run: |
          # Create the exact directory the action is looking in
          mkdir -p /home/runner/work/APITest/APITest

          # Copy all files to that directory
          cp -R ./* /home/runner/work/APITest/APITest/

          # Show contents to verify
          echo "Files copied to expected location:"
          ls -la /home/runner/work/APITest/APITest/

          # Verify servers.yaml exists in that location
          if [ -f /home/runner/work/APITest/APITest/servers.yaml ]; then
            echo "servers.yaml exists in the expected location"
          else
            echo "servers.yaml not found in the expected location"
          fi

      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: ${{ secrets.BUMP_DOC_ID }}
          token: ${{ secrets.BUMP_TOKEN }}
          file: openapi.yaml
