name: Deploy API Documentation to Bump.sh

on:
  push:
    branches: [main]
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  deploy-to-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fix YAML references and create symlinks
        run: |
          echo "Creating symbolic links for missing files..."

          # Create symlinks in the components directory
          ln -sf "$(pwd)/components/schemas/errors.yaml" "$(pwd)/components/errors.yaml"
          ln -sf "$(pwd)/components/schemas/cards.yaml" "$(pwd)/components/cards.yaml"
          ln -sf "$(pwd)/components/schemas/receipts.yaml" "$(pwd)/components/receipts.yaml"
          ln -sf "$(pwd)/components/schemas/transactions.yaml" "$(pwd)/components/transactions.yaml"

          # Create symlinks at the root level as well
          ln -sf "$(pwd)/components/schemas/errors.yaml" "$(pwd)/errors.yaml"
          ln -sf "$(pwd)/components/schemas/cards.yaml" "$(pwd)/cards.yaml"
          ln -sf "$(pwd)/components/schemas/receipts.yaml" "$(pwd)/receipts.yaml"
          ln -sf "$(pwd)/components/schemas/transactions.yaml" "$(pwd)/transactions.yaml"

          echo "Verifying symlinks..."
          ls -la
          ls -la components/

          # Check if the symlinks actually work
          if [ -f errors.yaml ]; then
            echo "errors.yaml is accessible"
            head -n 5 errors.yaml
          else
            echo "errors.yaml is not accessible"
          fi

      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: omni-v2
          token: ${{ secrets.BUMP_TOKEN }}
          file: openapi.yaml
