name: Deploy API Documentation to Bump.sh

on:
  push:
    branches: [main]
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  deploy-to-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Check for problematic $ref paths
        run: |
          echo "Checking for incorrect references to errors.yaml..."
          grep -r "'../errors.yaml#" --include="*.yaml" .
          grep -r "./components/errors.yaml" --include="*.yaml" .

          echo "Creating symbolic links to handle incorrect paths..."
          mkdir -p components
          ln -s components/schemas/errors.yaml components/errors.yaml
          ln -s components/schemas/cards.yaml components/cards.yaml
          ln -s components/schemas/receipts.yaml components/receipts.yaml
          ln -s components/schemas/transactions.yaml components/transactions.yaml

          echo "Verifying symbolic links..."
          ls -la components/

      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: omni-v2
          token: ${{ secrets.BUMP_TOKEN }}
          file: openapi.yaml
