name: Deploy API Documentation to Bump.sh

on:
  push:
    branches: [main]
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  deploy-to-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fix incorrect references in transactions.yaml
        run: |
          echo "Fixing references in transactions.yaml..."
          # Backup the original file
          cp components/schemas/transactions.yaml components/schemas/transactions.yaml.bak

          # Replace '../errors.yaml' with './errors.yaml'
          sed -i "s/'..\/errors.yaml/'.\\/errors.yaml/g" components/schemas/transactions.yaml

          # Check if references to cards.yaml and receipts.yaml need fixing
          if grep -q "'../cards.yaml" components/schemas/transactions.yaml; then
            echo "Fixing references to cards.yaml..."
            sed -i "s/'..\/cards.yaml/'.\\/cards.yaml/g" components/schemas/transactions.yaml
          fi

          if grep -q "'../receipts.yaml" components/schemas/transactions.yaml; then
            echo "Fixing references to receipts.yaml..."
            sed -i "s/'..\/receipts.yaml/'.\\/receipts.yaml/g" components/schemas/transactions.yaml
          fi

          # Check if references to transactions.yaml in webhooks.yaml need fixing
          if [ -f components/schemas/webhooks.yaml ]; then
            if grep -q "'../transactions.yaml" components/schemas/webhooks.yaml; then
              echo "Fixing references to transactions.yaml in webhooks.yaml..."
              cp components/schemas/webhooks.yaml components/schemas/webhooks.yaml.bak
              sed -i "s/'..\/transactions.yaml/'.\\/transactions.yaml/g" components/schemas/webhooks.yaml
            fi
          fi

          echo "Verifying changes..."
          grep -r "./errors.yaml" --include="*.yaml" components/schemas/

      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: omni-v2
          token: ${{ secrets.BUMP_TOKEN }}
          file: openapi.yaml
