name: Bump.sh API Documentation

on:
  push:
    branches:
      - main # or master, depending on your default branch
    paths:
      - 'openapi/**' # Only trigger when files in the openapi directory change

jobs:
  deploy-doc:
    name: Deploy API documentation to Bump.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy API documentation
        uses: bump-sh/github-action@v1
        with:
          doc: ${{ secrets.BUMP_DOC_ID }}
          token: ${{ secrets.BUMP_TOKEN }}
          file: openapi/openapi.yaml
