name: Deploy API Documentation to Bump.sh

on:
  push:
    branches: [main]
    paths:
      - '**/*.yaml'
      - '**/*.yml'
  workflow_dispatch:

jobs:
  deploy-to-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Bump.sh CLI
        run: |
          npm install -g bump-cli
          pip install --user pyyaml

      - name: Create basic reference resolver
        run: |
          cat > concat.py << 'EOF'
          import yaml
          import sys
          import os

          # Load the main OpenAPI file
          with open('openapi.yaml', 'r') as f:
              main_content = f.read()

          # Load the schemas file
          with open('./components/schemas.yaml', 'r') as f:
              schemas_content = f.read()

          # Load the topics file
          with open('./topics.yaml', 'r') as f:
              topics_content = f.read()

          # Output OpenAPI without trying to process it
          # This approach simply replaces references with file content directly
          main_content = main_content.replace("$ref: './components/schemas.yaml'", schemas_content.strip())
          main_content = main_content.replace("$ref: './topics.yaml'", topics_content.strip())

          # Write to new file
          with open('openapi-resolved.yaml', 'w') as f:
              f.write(main_content)

          print("Created openapi-resolved.yaml with direct content replacement")
          EOF

      - name: Concatenate files
        run: |
          python3 concat.py

      - name: Create fallback file if needed
        run: |
          # If the concatenation failed, just copy the original file
          if [ ! -f openapi-resolved.yaml ]; then
            echo "Creating basic copy as fallback..."
            cp openapi.yaml openapi-resolved.yaml
          fi

      - name: Deploy to Bump.sh
        id: deploy
        run: |
          echo "Deploying to Bump.sh..."
          bump deploy openapi-resolved.yaml --doc omni-v2 || bump deploy openapi.yaml --doc omni-v2
        env:
          BUMP_TOKEN: ${{ secrets.BUMP_TOKEN }}

      - name: Summary
        if: always()
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "* Original file: $(wc -c openapi.yaml | awk '{print $1}') bytes" >> $GITHUB_STEP_SUMMARY
          echo "* Resolved file: $(wc -c openapi-resolved.yaml | awk '{print $1}') bytes" >> $GITHUB_STEP_SUMMARY
          echo "* Status: ${{ steps.deploy.outcome }}" >> $GITHUB_STEP_SUMMARY
          echo "* Documentation URL: https://bump.sh/doc/omni-v2" >> $GITHUB_STEP_SUMMARY
