name: Deploy API Documentation to Bump.sh

on:
  push:
    branches: [main]
    paths:
      - '**/*.yaml'
      - '**/*.yml'

jobs:
  deploy-to-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Bump.sh CLI
        run: npm install -g bump-cli

      - name: Inline x-topics in openapi.yaml
        run: |
          echo "Fixing x-topics format..."

          # Get content from topics.yaml
          TOPICS_CONTENT=$(cat topics.yaml)

          # Make a backup
          cp openapi.yaml openapi.yaml.bak

          # Replace the $ref line with direct content
          sed -i '/x-topics:/,+1d' openapi.yaml

          # Add x-topics as inline content
          sed -i '/^openapi:/a x-topics:\n'"$TOPICS_CONTENT"'' openapi.yaml

          # Verify
          grep -A5 "x-topics:" openapi.yaml || echo "x-topics not found"

      - name: Deploy using Bump.sh CLI
        run: bump deploy openapi.yaml --doc omni-v2
        env:
          BUMP_TOKEN: ${{ secrets.BUMP_TOKEN }}
