name: Deploy API Documentation to Bump.sh

on:
  push:
    branches: [main]
    paths:
      - '**/*.yaml'
      - '**/*.yml'
  workflow_dispatch:

jobs:
  deploy-to-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Bump.sh CLI
        run: npm install -g bump-cli

      - name: Advanced Diagnostics
        run: |
          echo "Full diagnostic check..."

          echo "1. Examining openapi.yaml:"
          grep -n "x-topics" -A3 openapi.yaml

          echo "2. Testing reference syntax:"
          # Create a test file with a slightly different reference format
          cp openapi.yaml openapi-test.yaml

          # Replace the reference line with a variation to test
          sed -i 's|x-topics:.*|x-topics: { "$ref": "./topics.yaml" }|' openapi-test.yaml

          echo "Modified reference in test file:"
          grep -n "x-topics" -A3 openapi-test.yaml

      - name: Deploy test file to Bump.sh
        run: |
          echo "Deploying test file with modified reference..."
          bump deploy openapi-test.yaml --doc omni-v2
        env:
          BUMP_TOKEN: ${{ secrets.BUMP_TOKEN }}
