name: Bump.sh API Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy-doc:
    name: Deploy API documentation to Bump.sh
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Bump.sh CLI
        run: npm install -g @bump.sh/cli

      - name: Deploy with Bump.sh CLI
        run: |
          # Print debug info
          echo "Current directory:"
          pwd
          echo "Files in directory:"
          ls -la

          # Deploy using Bump CLI directly
          bump deploy openapi.yaml --doc ${{ secrets.BUMP_DOC_ID }} --token ${{ secrets.BUMP_TOKEN }}
        shell: bash
